//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisolCRM.DAL
{
    using System;
    
    public partial class fnRESIDENTCONTRACT
    {
        public int ID { get; set; }
        public Nullable<int> CITY { get; set; }
        public string HOUSE { get; set; }
        public string STREET { get; set; }
        public string TOC1 { get; set; }
        public string TOC2 { get; set; }
        public Nullable<int> BRANCH { get; set; }
        public string FAMILY { get; set; }
        public string NAME { get; set; }
        public string FATHERNAME { get; set; }
    }
}
