//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisolCRM.DAL
{
    using System;
    
    public partial class fnTAWDBRESCONTRACTCALC
    {
        public Nullable<int> BRANCH { get; set; }
        public Nullable<int> CALCINTERVAL { get; set; }
        public Nullable<short> CALCULATED { get; set; }
        public Nullable<decimal> DRAINAGECLCAMOUNT { get; set; }
        public Nullable<double> DRAINAGECLCGOODS { get; set; }
        public Nullable<decimal> DRAINAGESTMAMOUNT { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
