//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recame.DAL
{
    using System;
    
    public partial class fnTranslation
    {
        public string Language { get; set; }
        public int Id { get; set; }
        public int ObjectType { get; set; }
        public string Key { get; set; }
        public System.DateTimeOffset Modified { get; set; }
        public string Text { get; set; }
    }
}
