//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recame.DAL
{
    using System;
    
    public partial class fnTranslationEntry
    {
        public string LanguageId { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string Text { get; set; }
        public Nullable<int> TranslationId { get; set; }
    }
}
