//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recame.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecameEntities : DbContext
    {
        public RecameEntities()
            : base("name=RecameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<FoodShop> FoodShops { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuItemIngredient> MenuItemIngredients { get; set; }
    
        [DbFunction("RecameEntities", "fn_FoodShop")]
        public virtual IQueryable<fnFoodShop> fn_FoodShop(string language)
        {
            var languageParameter = language != null ?
                new ObjectParameter("Language", language) :
                new ObjectParameter("Language", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnFoodShop>("[RecameEntities].[fn_FoodShop](@Language)", languageParameter);
        }
    
        [DbFunction("RecameEntities", "fn_Ingredient")]
        public virtual IQueryable<fn_Ingredient_Result> fn_Ingredient()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Ingredient_Result>("[RecameEntities].[fn_Ingredient]()");
        }
    
        [DbFunction("RecameEntities", "fn_Menu")]
        public virtual IQueryable<fn_Menu_Result> fn_Menu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Menu_Result>("[RecameEntities].[fn_Menu]()");
        }
    
        [DbFunction("RecameEntities", "fn_MenuItem")]
        public virtual IQueryable<fn_MenuItem_Result> fn_MenuItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_MenuItem_Result>("[RecameEntities].[fn_MenuItem]()");
        }
    
        [DbFunction("RecameEntities", "fn_MenuItemIngredient")]
        public virtual IQueryable<fn_MenuItemIngredient_Result> fn_MenuItemIngredient()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_MenuItemIngredient_Result>("[RecameEntities].[fn_MenuItemIngredient]()");
        }
    }
}
