//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Translation()
        {
            this.FoodShops = new HashSet<FoodShop>();
            this.FoodShops1 = new HashSet<FoodShop>();
            this.TranslationEntries = new HashSet<TranslationEntry>();
        }
    
        public int Id { get; set; }
        public int ObjectType { get; set; }
        public System.DateTimeOffset Modified { get; set; }
        public string Key { get; set; }
        public byte[] UpdateVersion { get; set; }
        public Nullable<long> ObjectId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ExternalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodShop> FoodShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodShop> FoodShops1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranslationEntry> TranslationEntries { get; set; }
    }
}
