CREATE TABLE [dbo].[Language](
	[Id] [char](2) NOT NULL,
	[NumId] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[EnName] [nvarchar](255) NOT NULL,
	[ISOCode] [nvarchar](5) NULL,
 CONSTRAINT [PK_Language] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_Language] UNIQUE NONCLUSTERED 
(
	[NumId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
